version: "3"
services:
  countries-app:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - ./:/app 
      # ./ this bind the current directory: directory in container, so if make changes the container also have the changes.
      - /app/node_modules
      # when bound if i delete in the local project node_modules, it wont have effect the container, 
      # but it still keep watching the rest of the files
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres  
    environment:
      environment:
      POSTGRES_USER: ${user}
      POSTGRES_HOST: ${host}
      POSTGRES_DB: ${database}
      POSTGRES_PASSWORD: ${password}
      POSTGRES_PORT: ${port}
    env_file:
      - ./.env
    

